name: Common setup

description: Performs setup common to all our actions

inputs:
  os:
    required: true
  compiler:
    required: true
  platform:
    required: true
  config:
    required: true
  build-llvm:
    required: true
  use-cached-llvm:
    default: true
    required: false
runs:
  using: composite
  steps:
    - name: Add bash to PATH
      shell: pwsh
      if: ${{inputs.os == 'windows'}}
      run: |
        Add-Content -Path $env:GITHUB_PATH -Value "C:\\Program Files\\Git\\bin"
        Add-Content -Path $env:GITHUB_PATH -Value "C:\\Program Files\\Git\\usr\\bin"

    - name: Set up MSVC dev tools on Windows
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies (Linux only)
      if: inputs.os == 'linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev

    - name: Setup Node.js (Linux only)
      if: inputs.os == 'linux'
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - shell: bash
      run: |
        # Set up system dependencies

        # Install Ninja
        if ! command -v ninja; then
          case "${{inputs.os}}" in
            linux*) sudo apt-get install -y ninja-build;;
            windows*) choco install ninja;;
            macos*) brew install ninja;;
          esac
        fi

        # Install cross tools on Ubuntu
        if [[ "${{inputs.os}}" == linux* && "${{inputs.platform}}" == "aarch64" && "$(uname -m)" != "aarch64" ]]; then
          sudo apt-get install -y crossbuild-essential-arm64
        fi

        # Set compiler
        CC=${{inputs.compiler}}
        CXX=${{inputs.compiler}}
        # infer C++ compiler
        CXX=${CXX/gcc/g++}
        CXX=${CXX/clang/clang++}
        # Correct gcc version on older ubuntu
        if [[ "${{inputs.os}}" == linux* ]]; then
          gcc_version=$(gcc -dumpversion | cut -d'.' -f1)
          if [ "$gcc_version" -lt 10 ]; then
            CC=${CC/gcc/gcc-10}
            CXX=${CXX/g++/g++-10}
          fi
        fi
        # Export
        echo "CC=$CC" >> "$GITHUB_ENV"
        echo "CXX=$CXX" >> "$GITHUB_ENV"

        # Some useful variables
        config=${{inputs.config}}
        cmake_config=$(echo "${{inputs.config}}" | sed '
            s/^debug$/Debug/
            s/^release$/Release/
            s/^releaseWithDebugInfo$/RelWithDebInfo/
            s/^minSizeRelease$/MinSizeRel/
        ')
        bin_dir=$(pwd)/build/$cmake_config/bin
        lib_dir=$(pwd)/build/$cmake_config/lib
        echo "config=$config" >> "$GITHUB_ENV"
        echo "cmake_config=$cmake_config" >> "$GITHUB_ENV"
        echo "bin_dir=$bin_dir" >> "$GITHUB_ENV"
        echo "lib_dir=$lib_dir" >> "$GITHUB_ENV"

    # Setup LLVM from GCS (or build if missing)
    - name: Setup LLVM from GCS
      if: inputs.build-llvm == 'true' && inputs.use-cached-llvm == 'true'
      uses: ./.github/actions/setup-llvm-from-gcs
      with:
        os: ${{ inputs.os }}
        compiler: ${{ inputs.compiler }}
        platform: ${{ inputs.platform }}
        llvm-hash: ${{ hashFiles('external/build-llvm.sh') }}
        build-if-missing: "true"
        github-token: ${{ github.token }}

    - name: Set environment variable for CMake
      shell: bash
      run: |
        if [ "${{inputs.build-llvm}}" == "true" ]; then
          echo "LLVM_DIR=${{ github.workspace }}/build/llvm-project-install" >> "$GITHUB_ENV"
          echo "Clang_DIR=${{ github.workspace }}/build/llvm-project-install" >> "$GITHUB_ENV"
        fi

    # Put spirv-tools in path
    - shell: bash
      run: |
        win_platform="${{ inputs.platform }}"
        win_platform="${win_platform//x86_64/x64}"
        case "${{inputs.os}}" in
          windows*) echo "${{github.workspace}}/external/slang-binaries/spirv-tools/windows-$win_platform/bin" >> "$GITHUB_PATH";;
          linux*) echo "${{github.workspace}}/external/slang-binaries/spirv-tools/$(uname -m)-linux/bin" >> "$GITHUB_PATH";;
        esac

      # Note: ccache for Windows self-hosted has been replaced by sccache
      # sccache is set up in ci-slang-build.yml for all platforms
