name: Setup sccache
description: Install and configure sccache with local disk backend for Linux, macOS, and Windows

inputs:
  platform:
    description: "Platform: linux, macos, or windows"
    required: true

runs:
  using: composite
  steps:
    # Install sccache
    - name: Install sccache (Linux)
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        # Detect architecture
        ARCH=$(uname -m)
        if [[ "$ARCH" == "x86_64" ]]; then
          SCCACHE_ARCH="x86_64-unknown-linux-musl"
        elif [[ "$ARCH" == "aarch64" ]]; then
          SCCACHE_ARCH="aarch64-unknown-linux-musl"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi

        echo "Installing sccache for $ARCH ($SCCACHE_ARCH)"
        curl -fL https://github.com/mozilla/sccache/releases/download/v0.7.4/sccache-v0.7.4-${SCCACHE_ARCH}.tar.gz | tar xz

        # Try with sudo if available, otherwise install directly (for containers running as root)
        if command -v sudo &> /dev/null; then
          sudo mv sccache-v0.7.4-${SCCACHE_ARCH}/sccache /usr/local/bin/
          sudo chmod +x /usr/local/bin/sccache
        else
          mv sccache-v0.7.4-${SCCACHE_ARCH}/sccache /usr/local/bin/
          chmod +x /usr/local/bin/sccache
        fi

        sccache --version

    - name: Install sccache (macOS)
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        brew install sccache
        sccache --version

    - name: Install sccache (Windows)
      if: inputs.platform == 'windows'
      shell: pwsh
      run: |
        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          Write-Host "✅ sccache already installed: $(sccache --version)"
        } else {
          # Verify x64 architecture
          if ($env:PROCESSOR_ARCHITECTURE -ne "AMD64") {
            Write-Host "Unsupported Windows architecture: $env:PROCESSOR_ARCHITECTURE"
            exit 1
          }

          Write-Host "Installing sccache for Windows..."
          $installDir = Join-Path $env:RUNNER_TEMP "sccache-bin"
          New-Item -ItemType Directory -Force -Path $installDir | Out-Null

          # Use .zip release to avoid tar path issues on Windows
          $zipFile = Join-Path $env:RUNNER_TEMP "sccache.zip"
          curl.exe -L -o $zipFile https://github.com/mozilla/sccache/releases/download/v0.7.4/sccache-v0.7.4-x86_64-pc-windows-msvc.zip
          Expand-Archive -Path $zipFile -DestinationPath $env:RUNNER_TEMP -Force
          Move-Item (Join-Path $env:RUNNER_TEMP "sccache-v0.7.4-x86_64-pc-windows-msvc\sccache.exe") (Join-Path $installDir "sccache.exe")
          $installDir | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          & (Join-Path $installDir "sccache.exe") --version
        }

    # Configure sccache with local disk backend
    - name: Configure sccache (Unix)
      if: inputs.platform != 'windows'
      shell: bash
      run: |
        echo "SCCACHE_CACHE_ZSTD_LEVEL=3" >> $GITHUB_ENV
        echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
        echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV
        echo "SCCACHE_BASE_DIR=$PWD" >> $GITHUB_ENV
        echo "SCCACHE_CACHE_SIZE=2G" >> $GITHUB_ENV
        echo "SCCACHE_DIR=/tmp/.cache/sccache" >> $GITHUB_ENV
        echo "sccache_cache_dir=/tmp/.cache/sccache" >> $GITHUB_ENV
        mkdir -p /tmp/.cache/sccache

        sccache_path=$(which sccache)
        echo "sccache_path=$sccache_path" >> $GITHUB_ENV

        echo "🔧 sccache configured for local disk backend"

    - name: Configure sccache (Windows)
      if: inputs.platform == 'windows'
      shell: pwsh
      run: |
        "SCCACHE_CACHE_ZSTD_LEVEL=3" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "SCCACHE_IGNORE_SERVER_IO_ERROR=1" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "SCCACHE_IDLE_TIMEOUT=0" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "SCCACHE_BASE_DIR=$PWD" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "SCCACHE_CACHE_SIZE=2G" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

        # Set Windows cache directory
        $sccacheDir = "C:\sccache"
        if (-not (Test-Path $sccacheDir -ErrorAction SilentlyContinue)) {
          try {
            New-Item -ItemType Directory -Force -Path $sccacheDir | Out-Null
          } catch {
            $sccacheDir = Join-Path $env:RUNNER_TEMP "sccache"
            New-Item -ItemType Directory -Force -Path $sccacheDir | Out-Null
          }
        }
        "SCCACHE_DIR=$sccacheDir" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "sccache_cache_dir=$sccacheDir" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

        $sccachePath = (Get-Command sccache).Source
        "sccache_path=$sccachePath" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

        Write-Host "🔧 sccache configured for local disk backend ($sccacheDir)"
